export {
  ATMOSPHERIC_PRESSURE_KPA,
  FULL_BOOST_MAP_KPA,
  KPA_TO_PSI,
  TACH_MAX_RPM,
  TACH_MIN_RPM,
  TACH_REDLINE_RPM,
  TRANSMISSION_GEAR_RATIOS,
  FINAL_DRIVE_RATIO,
  DRIVEN_TIRE_DIAMETER_INCHES,
  TRANSFER_CASE_LOW_RATIO,
  TANK_CAPACITY_GALLONS
} from "../../../../settings/vehicleConfig.js";
